apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe
  namespace: ${NAMESPACE}  # This will be dynamically replaced (test, prod, etc.)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipe
  template:
    metadata:
      labels:
        app: pipe
    spec:
      containers:
      - name: pipe
        image: ${DOCKER_HUB_REPO}:${DOCKER_TAG}  # This will be replaced with the latest image tag dynamically
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ${NAMESPACE}  # This will also be dynamically replaced (test, prod, etc.)
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pipe
